(source gnu)
(source melpa)

(depends-on "gtags" :git "https://github.com/voins/gtags.git")
(depends-on "auto-complete")
(depends-on "ace-jump-mode")
(depends-on "ido-vertical-mode")
(depends-on "magit")
(depends-on "ag")
(depends-on "elscreen")
(depends-on "expand-region")
(depends-on "undo-tree")
(depends-on "markdown-mode")
(depends-on "wanderlust")
(depends-on "ox-textile" :git "https://github.com/yashi/org-textile.git")
